# Generated by Django 2.1.1 on 2018-12-12 14:36

from django.db import migrations

def backfill_popularity(apps, schema_editor):
    # We can't import the Book model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Book = apps.get_model('sample_app', 'Book')

    all_titles = Book.objects.all().values_list('title', flat=True)
    max_title_length = max([len(title) for title in all_titles])

    for book in Book.objects.all():
        book.popularity = len(book.title) / max_title_length * 5
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_book_popularity'),
    ]

    operations = [
        migrations.RunPython(backfill_popularity)
    ]
