# Generated by Django 2.1.1 on 2018-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_auto_20181212_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='popularity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
